<?php

namespace ContainerRejIZEx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_URjxCKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u_RjxCK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u_RjxCK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'GenreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
        ], [
            'GenreRepository' => 'App\\Repository\\GenreRepository',
        ]);
    }
}
