<?php

namespace ContainerRejIZEx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_62DvxlAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.62DvxlA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.62DvxlA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'BookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
        ], [
            'BookRepository' => 'App\\Repository\\BookRepository',
        ]);
    }
}
