<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRejIZEx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRejIZEx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRejIZEx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRejIZEx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRejIZEx\App_KernelDevDebugContainer([
    'container.build_hash' => 'RejIZEx',
    'container.build_id' => 'c65ecfe2',
    'container.build_time' => 1608729400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRejIZEx');
