<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'Book_index' => [[], ['_controller' => 'App\\Controller\\BookController::index'], [], [['text', '/Book/']], [], []],
    'Book_new' => [[], ['_controller' => 'App\\Controller\\BookController::new'], [], [['text', '/Book/new']], [], []],
    'Book_show' => [['id'], ['_controller' => 'App\\Controller\\BookController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Book']], [], []],
    'Book_edit' => [['id'], ['_controller' => 'App\\Controller\\BookController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/Book']], [], []],
    'Book_delete' => [['id'], ['_controller' => 'App\\Controller\\BookController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Book']], [], []],
    'find_Book_by_name' => [['name'], ['_controller' => 'App\\Controller\\BookController::findAllByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/Book/find']], [], []],
    'Genre_index' => [[], ['_controller' => 'App\\Controller\\GenreController::index'], [], [['text', '/Genre/']], [], []],
    'Genre_new' => [[], ['_controller' => 'App\\Controller\\GenreController::new'], [], [['text', '/Genre/new']], [], []],
    'find_Genre_by_name' => [['name'], ['_controller' => 'App\\Controller\\GenreController::findAllByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/Genre/find']], [], []],
    'Genre_show' => [['id'], ['_controller' => 'App\\Controller\\GenreController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Genre']], [], []],
    'Genre_edit' => [['id'], ['_controller' => 'App\\Controller\\GenreController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/Genre']], [], []],
    'Genre_delete' => [['id'], ['_controller' => 'App\\Controller\\GenreController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Genre']], [], []],
];
