<?php

namespace ContainerRa6K5mV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8TFCTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8_TFC_t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8_TFC_t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.Qh463K9', 'get_ServiceLocator_Qh463K9Service', true],
            'App\\Controller\\BookController::edit' => ['privates', '.service_locator.Qh463K9', 'get_ServiceLocator_Qh463K9Service', true],
            'App\\Controller\\BookController::findAllByName' => ['privates', '.service_locator.62DvxlA', 'get_ServiceLocator_62DvxlAService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.62DvxlA', 'get_ServiceLocator_62DvxlAService', true],
            'App\\Controller\\BookController::show' => ['privates', '.service_locator.Qh463K9', 'get_ServiceLocator_Qh463K9Service', true],
            'App\\Controller\\GenreController::delete' => ['privates', '.service_locator.mqxDq8z', 'get_ServiceLocator_MqxDq8zService', true],
            'App\\Controller\\GenreController::edit' => ['privates', '.service_locator.mqxDq8z', 'get_ServiceLocator_MqxDq8zService', true],
            'App\\Controller\\GenreController::findAllByName' => ['privates', '.service_locator.u_RjxCK', 'get_ServiceLocator_URjxCKService', true],
            'App\\Controller\\GenreController::index' => ['privates', '.service_locator.u_RjxCK', 'get_ServiceLocator_URjxCKService', true],
            'App\\Controller\\GenreController::show' => ['privates', '.service_locator.mqxDq8z', 'get_ServiceLocator_MqxDq8zService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.Qh463K9', 'get_ServiceLocator_Qh463K9Service', true],
            'App\\Controller\\BookController:edit' => ['privates', '.service_locator.Qh463K9', 'get_ServiceLocator_Qh463K9Service', true],
            'App\\Controller\\BookController:findAllByName' => ['privates', '.service_locator.62DvxlA', 'get_ServiceLocator_62DvxlAService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.62DvxlA', 'get_ServiceLocator_62DvxlAService', true],
            'App\\Controller\\BookController:show' => ['privates', '.service_locator.Qh463K9', 'get_ServiceLocator_Qh463K9Service', true],
            'App\\Controller\\GenreController:delete' => ['privates', '.service_locator.mqxDq8z', 'get_ServiceLocator_MqxDq8zService', true],
            'App\\Controller\\GenreController:edit' => ['privates', '.service_locator.mqxDq8z', 'get_ServiceLocator_MqxDq8zService', true],
            'App\\Controller\\GenreController:findAllByName' => ['privates', '.service_locator.u_RjxCK', 'get_ServiceLocator_URjxCKService', true],
            'App\\Controller\\GenreController:index' => ['privates', '.service_locator.u_RjxCK', 'get_ServiceLocator_URjxCKService', true],
            'App\\Controller\\GenreController:show' => ['privates', '.service_locator.mqxDq8z', 'get_ServiceLocator_MqxDq8zService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\BookController::edit' => '?',
            'App\\Controller\\BookController::findAllByName' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::show' => '?',
            'App\\Controller\\GenreController::delete' => '?',
            'App\\Controller\\GenreController::edit' => '?',
            'App\\Controller\\GenreController::findAllByName' => '?',
            'App\\Controller\\GenreController::index' => '?',
            'App\\Controller\\GenreController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\BookController:edit' => '?',
            'App\\Controller\\BookController:findAllByName' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:show' => '?',
            'App\\Controller\\GenreController:delete' => '?',
            'App\\Controller\\GenreController:edit' => '?',
            'App\\Controller\\GenreController:findAllByName' => '?',
            'App\\Controller\\GenreController:index' => '?',
            'App\\Controller\\GenreController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
